### ISSUE TITLE
Create Developer Experience and Community Success handbook

### ISSUE THREAD

**Issue by dplanella** [linuxfoundation/devex-and-commsuccess#84]
## Initiative Details

- [ ] Define initial handbook structure
- [ ] Define handbook infrastructure: tech stack and hosting
- [ ] Create initial handbook content
- [ ] Document how to edit the handbook
- [ ] Team members do their first edits to handbook and provide feedback
- [ ] Deploy handbook

## Highlights

1. Handbook online at https://linuxfoundation.github.io/devex-and-commsuccess
